- id: 0
  x: -5.0
  y: -5.0
  z: 2.0
  roll: 0.0
  pitch: 0.3
  yaw: 0.7853
- id: 1
  x: 5.0
  y: 5.0
  z: 2.0
  roll: 0.0
  pitch: 0.3
  yaw: -2.3571
- id: 2
  x: 5.0
  y: -5.0
  z: 2.0
  roll: 0.0
  pitch: 0.3
  yaw: 2.3571
- id: 3
  x: -5.0
  y: 5.0
  z: 2.0
  roll: 0.0
  pitch: 0.3
  yaw: -0.7853
